spring.application.name=ecommerce-backend

# Production
JWT_SECRET=dWznpvSmB05Xt/NpmCB+zEZPgs0y/Hii2gFEAH66E80=
spring.datasource.url=jdbc:postgresql://ep-cold-cell-ac3a1cnd-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DcIsxQ6q7Pir
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect